export interface LeadArgs {
  name?: string;
  phone?: string;
  product?: string;
  gsm?: string;
  location?: string;
  /** When the customer said we may call — "after 5 pm", "morning", "anytime". */
  callTime?: string;
  requirement?: string;
  summary?: string;
  /** Captured for context but not written to a Sheet column. */
  company?: string;
  email?: string;
  quantity?: string;
  size?: string;
}

/**
 * Customers answer the GSM question with a bare number — "220" — and a bare
 * number lands in the Sheet as a number, right-aligned and with no unit. Append
 * the unit unless the answer already carries one, so "1.5 mm" or "300 GSM" are
 * left exactly as the customer said them.
 */
function withGsmUnit(value: string): string {
  const trimmed = value.trim();



  
  if (!trimmed) return '';
  return /^[0-9., -]+$/.test(trimmed) ? `${trimmed} GSM` : trimmed;
}

/**
 * The Apps Script picks each value out by name and writes it to a fixed column,
 * so an unknown key is ignored and a missing one just leaves that cell blank —
 * neither shifts the row. Both casings of gsm / requirement are still sent
 * because the deployed script accepts either.
 * Timestamp is generated by the script itself, so it is not sent.
 */
function toSheetRow(args: LeadArgs): Record<string, string> {
  const gsm = withGsmUnit(args.gsm ?? '');
  const requirement = args.requirement ?? '';

  return {
    name: args.name ?? '',
    phone: args.phone ?? '',
    product: args.product ?? '',
    gsm,
    GSM: gsm,
    location: args.location ?? '',
    callTime: args.callTime ?? '',
    requirement,
    Requirement: requirement,
    summary: args.summary ?? '',
    source: 'Website Chatbot',
  };
}

/**
 * The Apps Script answers HTTP 200 even when it failed, putting the real
 * outcome in the body as {"success":false,"error":"..."}. Trust the body.
 */
function scriptSucceeded(body: string): { ok: boolean; error?: string } {
  try {
    const parsed = JSON.parse(body) as { success?: boolean; error?: string };
    if (parsed.success === false) return { ok: false, error: parsed.error ?? 'unknown script error' };
    return { ok: true };
  } catch {
    return { ok: true }; // non-JSON reply: fall back to the HTTP status
  }
}

export async function submitLead(
  webhookUrl: string,
  args: LeadArgs,
): Promise<{ ok: boolean; detail: string }> {
  if (!webhookUrl) {
    console.error('[lead] LEAD_WEBHOOK_URL is not set — nothing was saved.');
    return { ok: false, detail: 'webhook not configured' };
  }

  const row = toSheetRow(args);

  try {
    const res = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(row),
      redirect: 'follow',
      signal: AbortSignal.timeout(15_000),
    });

    const detail = (await res.text()).slice(0, 300);

    if (!res.ok) {
      console.error(`[lead] Apps Script returned ${res.status}: ${detail}`);
      return { ok: false, detail };
    }

    const verdict = scriptSucceeded(detail);
    if (!verdict.ok) {
      console.error(`[lead] script rejected the row: ${verdict.error}`);
      return { ok: false, detail };
    }

    return { ok: true, detail };
  } catch (error) {
    const detail = error instanceof Error ? error.message : 'unknown error';
    console.error(`[lead] submission failed: ${detail}`);
    return { ok: false, detail };
  }
}
